---
###################################################################################
#
#  Install Block
#

- name: Install Loki Package
  when: loki_state == 'present'
  block:
    - name: Is loki running?
      ansible.builtin.include_tasks:
        file: "../../shared/any/tasks/is-service-running.yml"
      vars:
        service_name: loki.service

    # .....................................................................................
    # only install if not running or loki_force_reload
    - name: Loki package install
      ansible.builtin.include_tasks:
        file: "../../shared/grafana/tasks/{{ ansible_distribution }}-install.yml"
      vars:
        package: ["loki", "logcli"]
      when: service_running is false or loki_force_reload

    ##################
    # Configure

    - name: Template config to  /etc/loki/config.yml
      become: true
      ansible.builtin.template:
        src: config.yml.j2
        dest: /etc/loki/config.yml
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart loki

- name: Ensure loki group and user exist
  block:
    - name: Create loki group
      group:
        name: loki
        system: yes
        state: present

    - name: Add loki user to loki group
      user:
        name: loki
        group: loki
        state: present

- name: Prepare Loki directories
  block:
    - name: Create Loki directories with consistent permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: loki
        group: loki
        mode: "0770"
        modification_time: preserve
        access_time: preserve
      loop:
        - /tmp/loki
        # - /tmp/loki/tsdb-shipper-active
        # - /tmp/loki/tsdb-shipper-active/scratch
        - /var/lib/loki
        - /var/lib/loki/chunks
        - /var/lib/loki/rules
      register: loki_dirs

    # - name: Debug directory changes
    #   debug:
    #     var: loki_dirs

    - name: Ensure consistent SELinux context
      command: restorecon -Rv "{{ item }}"
      loop:
        - /tmp/loki
        - /var/lib/loki
      when:
        - ansible_selinux.status == 'enabled'
        - loki_dirs.changed

###################################################################################
#
#  Remove Block
#
- name: Remove Loki Service
  when: loki_state == 'absent'
  block:
    # .................................................................
    - name: Package remove
      ansible.builtin.include_tasks:
        file: "../../shared/any/tasks/{{ ansible_distribution }}-rm.yml"
      vars:
        package: loki
        service_name: loki.service

    # .................................................................
    - name: "Remove the config files /etc/loki"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      become: true
      loop:
        - /etc/loki
        - /etc/default/loki
      when: loki_delete_config

      # .................................................................
    - name: "Remove the date files /var/lib/loki/"
      ansible.builtin.file:
        path: "/var/lib/loki/*"
        state: absent
      become: true
      when: loki_delete_data
