---
- name: Verify
  hosts: all
  become: true
  vars:
    # Only check container and network health
    check_services: false
    molecule_nolog: true
    on_github: "{{ lookup('env', 'IN_GITHUB_CI', default=false) }}"

  tasks:
    #
    # .....................................................................
    #
    - name: Ensure verify_output directory exists
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

    # .....................................................................
    - name: Debug information
      debug:
        msg:
          - "GithubCi: {{ on_github }}"
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_distribution }}"
          - "Testing capability: {{ testing_capabilities }}"

    # .......................................................................
    - name: Run container diagnostics
      include_tasks:
        file: "{{ project_root }}/molecule/shared/diagnostics/tasks/main.yml"
      vars:
        report_suffix: "pre-verify"

    # .......................................................................
    - name: Run capability-specific verifications
      include_tasks: "{{ project_root }}/molecule/shared/verify/verify-{{ capability }}.yml"
      loop: "{{ testing_capabilities }}"
      loop_control:
        loop_var: capability
        label: "Verifying {{ capability }} capability"
