---
- name: Verify
  hosts: all
  become: true
  serial: "{{ lookup('env', 'MOLECULE_SERIAL', default='0') }}"

  vars:
    # Only check container and network health
    check_services: false
    molecule_nolog: true
    verify_timestamp: "{{ ansible_date_time.iso8601 }}"
    on_github: "{{ lookup('env', 'IN_GITHUB_CI', default=false) }}"

  tasks:
    #
    # .....................................................................
    #
    - name: Ensure verify_output directory exists
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

    # .....................................................................
    - name: Debug information
      debug:
        msg:
          - "GithubCi: {{ on_github }}"
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_distribution }}"
          - "Testing capability: {{ testing_capabilities }}"

    # .......................................................................
    - name: Run container diagnostics
      ansible.builtin.include_tasks:
        file: "{{ project_root }}/molecule/shared/diagnostics/main.yml"
      vars:
        report_suffix: "pre-verify"

    # .......................................................................
    - name: Run capability-specific verifications
      include_tasks: "verify-{{ capability }}.yml"
      loop: "{{ testing_capabilities }}"
      loop_control:
        loop_var: capability
        label: "Verifying {{ capability }} capability"

    # .......................................................................
    - name: Create verification status map
      set_fact:
        verification_status: >-
          {{
            verification_status | default({}) | combine(
              { capability: hostvars[inventory_hostname][capability + '_verify_failed'] | default(false) }
            )
          }}
      loop: "{{ testing_capabilities }}"
      loop_control:
        loop_var: capability

    # .......................................................................
    - name: Final verification check
      fail:
        msg: "Verifications failed: {{ verification_status | dict2items | selectattr('value', 'true') | map(attribute='key') | list | join(', ') }}"
      when: verification_status.values() | list | select('true') | list | length > 0

    # .......................................................................
    - name: Run Gitlab CI only tasks
      when: on_github
      ansible.builtin.include_tasks: "verify-github.yml"
