---
name: CI

on:
  push:
    branches: [main, master]
    paths:
      - 'roles/**'
      - 'molecule/**'
      - '.github/**'
    # paths-ignore:
    #   - "**.md"
  pull_request:
    branches: [main, master]
    paths:
      - 'roles/**'
      - 'molecule/**'
    # paths-ignore:
    #   - "**.md"
  # Allow manual trigger on any branch (including dev)
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: '*'


# ...............................................................
#  SMELL I have not had much luck with vars in here.  revisit it later.
#      
env:
  DEBUG_MODE: save   # OR none OR interactive
  MOLECULE_NO_LOG: false
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

# ...............................................................
# this where github-ci gets it's "steps"
# things to know
# - env vars is how you pass information into the molecule.  
# - use playbooks to pass those into the ansible tasks/roles/modules
# - There is a test matrix capability, but allowing molecule 
#     to build the tests works better
# - the stage playbooks apply to all works, but it's far from elegant
# - You can put env vars in a step,  note that I do that for the molecule
#     
#
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    timeout-minutes: 60  # Add timeout protection
    strategy:
      fail-fast: false
      # max-parallel: 1  # Consider if parallel runs are desired
    env:
      DEBUG_MODE: save   
      MOLECULE_NO_LOG: false
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      # MOLECULE_DESTROY: ${{ github.event_name != 'pull_request' }}  # Keep containers on PR
      ANSIBLE_LOCALHOST_WARNING: false
      MOLECULE_VERIFY_RETRY: 3  # Add retry capability

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: main/.wiki
          token: ${{ secrets.WIKI_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Pull Docker images
        run: |
          docker pull ghcr.io/jackaltx/testing-containers/debian12-ssh:latest

        # docker pull ghcr.io/jackaltx/testing-containers/rocky93-ssh:latest
        # docker pull ghcr.io/jackaltx/testing-containers/ubuntu24-ssh:latest

      # claude:  should we pass this in as an array.  my lab will have single-board-computer clusters. I may want to do ARM64
      - name: Create anbible/molecule directories
        run: |
          mkdir -p log

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ansible-core==2.18.1 \
            molecule==24.12.0 \
            molecule-plugins==23.5.3 \
            ansible-lint==24.12.1 \
            yamllint==1.35.1 \
            docker \
            jmespath

      # ......................................................................
      - name: Debug GitHub context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repo: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"

      # .......................................................................
      # TODO: This feels wrong....it works.  
      # I would it make sense to read the local project requirements? 
      # I need to understand how that works locally as a developers machine is
      # rarely a good test of an integration
      # 
      - name: Install galaxy requirements
        run: |
          ansible-galaxy collection install community.general

      # .......................................................................
      # TODO:  move the wiki update logit a run step
      # this is a github only action.  I want to create a "wiki page" and a "notice" where required
      #
      - name: Run Molecule tests across all distros
        run: molecule test -s github
        continue-on-error: ${{ env.DEBUG_MODE != 'none' }}
        env:
          IN_GITHUB_CI: true
          LOG_DURATION: "5m"
          GITHUB_WORKSPACE: ${{ github.workspace }}/main
          MOLECULE_DISTRO: ${{ matrix.distro }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

      # .......................................................................
      # .......................................................................
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-test-results
          path: verify_output
          retention-days: 5  # Limit storage usage
          if-no-files-found: warn

 
      # .......................................................................
      # .......................................................................
      - name: Aggregate and publish results
        if: always()  # Run even if molecule tests fail
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}  # Missing auth token
        run: |
          echo "Processing test results..."
          
          # First handle individual distribution gists
          for distro in verify_output/*/; do
            if [ -f "${distro}/gist_content.md" ]; then
              distro_name=$(basename $distro)
              echo "Processing ${distro_name} results..."
              
              # Append git/build context to gist
              {
                echo "## Build Context"
                echo "- Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                echo "- Branch: ${{ github.ref_name }}"
                echo "- Commit: ${{ github.sha }}"
                echo "- Triggered by: ${{ github.event_name }}"
              } >> "${distro}/gist_content.md"
              
              # Create/update gist for this distro
              if ! gh gist create "${distro}/gist_content.md" \
                --public \
                --desc "Test Results for ${distro_name} (${GITHUB_SHA:0:7})"; then
                echo "Failed to create gist for ${distro_name}"
                exit 1
              fi
            else
              echo "Warning: No gist content found for ${distro_name}"
            fi
          done

      # --------------------------------------------------------------------------------------------
      # --------------------------------------------------------------------------------------------
      - name: Create job summary
        if: always()
        run: |
          {
            echo "# Test Run Summary"
            echo "- Status: success"
            echo "- Duration: "
            echo "## Distribution Results"
            for d in verify_output/*/; do
              distro_name=$(basename $d)
              echo -n "- ${distro_name}: "
              if [ -f "${d}/gist_content.md" ] && [ -f "${d}/wiki_content.md" ]; then
                echo "✅"
                echo "  - Gist Content: ✓"
                echo "  - Wiki Content: ✓"
              else
                echo "❌"
                [ -f "${d}/gist_content.md" ] && echo "  - Gist Content: ✓" || echo "  - Gist Content: ✗"
                [ -f "${d}/wiki_content.md" ] && echo "  - Wiki Content: ✓" || echo "  - Wiki Content: ✗"
              fi
            done
            
            echo "## File Structure"
            ls -R verify_output/
          } >> $GITHUB_STEP_SUMMARY