---
- name: Debian Grafana package install block
  become: true
  block:
    #
    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download and install Grafana GPG key
      ansible.builtin.shell:
        cmd: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg"
      args:
        creates: /etc/apt/keyrings/grafana.gpg

    - name: Set correct permissions on GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/grafana.gpg
        mode: "0644"

    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
        state: present
        filename: grafana
        update_cache: yes

    - name: "Install {{ package }} OSS debian package"
      ansible.builtin.apt:
        state: present
        update_cache: true
        name: "{{ package }}"
